export enum EEventType {
    UNKNOWN = 'UNKNOWN',
    ANY = 'ANY',
    LOG = 'LOG',
    DOCUMENT_OPEN = 'DOCUMENT_OPEN',
    DOCUMENT_CHANGE = 'DOCUMENT_CHANGE',
    DOCUMENT_FOCUS = 'DOCUMENT_FOCUS',
    DOCUMENT_SAVE = 'DOCUMENT_SAVE',
    ACTION = 'ACTION',
    KEY = 'KEY',
    FRAME_IN = 'FRAME_IN',
    FRAME_OUT = 'FRAME_OUT',
    DEVICE_INFO = 'DEVICE_INFO',
    PLUGIN_INFO = 'PLUGIN_INFO'
}
